### ISSUE TITLE
[3.3.0] 4.21 crashes with trigger mouse move

### ISSUE THREAD

**Issue by Invius** [getnamo/BLUI-Unreal#14] opened 2019-03-14 16:57 UTC
```
`LoginId:c5f839384123094ad2edcf9997f27f76
EpicAccountId:413eebd000db4d61a5aa7cb057e473f0

Access violation - code c0000005 (first/second chance not available)

libcef
UE4Editor_Blu
UE4Editor_Blu
UE4Editor_CoreUObject!UFunction::Invoke() [d:\build\++ue4\sync\engine\source\runtime\coreuobject\private\uobject\class.cpp:4861]
UE4Editor_CoreUObject!UObject::CallFunction() [d:\build\++ue4\sync\engine\source\runtime\coreuobject\private\uobject\scriptcore.cpp:816]
UE4Editor_CoreUObject!UObject::ProcessContextOpcode() [d:\build\++ue4\sync\engine\source\runtime\coreuobject\private\uobject\scriptcore.cpp:2330]
UE4Editor_CoreUObject!UObject::ProcessInternal() [d:\build\++ue4\sync\engine\source\runtime\coreuobject\private\uobject\scriptcore.cpp:1031]
UE4Editor_CoreUObject!UObject::CallFunction() [d:\build\++ue4\sync\engine\source\runtime\coreuobject\private\uobject\scriptcore.cpp:940]
UE4Editor_CoreUObject!UObject::ProcessInternal() [d:\build\++ue4\sync\engine\source\runtime\coreuobject\private\uobject\scriptcore.cpp:1031]
UE4Editor_CoreUObject!UFunction::Invoke() [d:\build\++ue4\sync\engine\source\runtime\coreuobject\private\uobject\class.cpp:4861]
UE4Editor_CoreUObject!UObject::ProcessEvent() [d:\build\++ue4\sync\engine\source\runtime\coreuobject\private\uobject\scriptcore.cpp:1480]
UE4Editor_Engine!AActor::ProcessEvent() [d:\build\++ue4\sync\engine\source\runtime\engine\private\actor.cpp:713]
UE4Editor_Engine!UPlayerInput::ProcessInputStack() [d:\build\++ue4\sync\engine\source\runtime\engine\private\userinterface\playerinput.cpp:1311]
UE4Editor_Engine!APlayerController::ProcessPlayerInput() [d:\build\++ue4\sync\engine\source\runtime\engine\private\playercontroller.cpp:2476]
UE4Editor_Engine!APlayerController::TickPlayerInput() [d:\build\++ue4\sync\engine\source\runtime\engine\private\playercontroller.cpp:4404]
UE4Editor_Engine!APlayerController::PlayerTick() [d:\build\++ue4\sync\engine\source\runtime\engine\private\playercontroller.cpp:2137]
UE4Editor_Engine!APlayerController::TickActor() [d:\build\++ue4\sync\engine\source\runtime\engine\private\playercontroller.cpp:4543]
UE4Editor_Engine!FActorTickFunction::ExecuteTick() [d:\build\++ue4\sync\engine\source\runtime\engine\private\actor.cpp:137]
UE4Editor_Engine!TGraphTask<FTickFunctionTask>::ExecuteTask() [d:\build\++ue4\sync\engine\source\runtime\core\public\async\taskgraphinterfaces.h:829]
UE4Editor_Core!FNamedTaskThread::ProcessTasksNamedThread() [d:\build\++ue4\sync\engine\source\runtime\core\private\async\taskgraph.cpp:679]
UE4Editor_Core!FNamedTaskThread::ProcessTasksUntilQuit() [d:\build\++ue4\sync\engine\source\runtime\core\private\async\taskgraph.cpp:575]
UE4Editor_Core!FTaskGraphImplementation::WaitUntilTasksComplete() [d:\build\++ue4\sync\engine\source\runtime\core\private\async\taskgraph.cpp:1444]
UE4Editor_Engine!FTickTaskSequencer::ReleaseTickGroup() [d:\build\++ue4\sync\engine\source\runtime\engine\private\ticktaskmanager.cpp:556]
UE4Editor_Engine!FTickTaskManager::RunTickGroup() [d:\build\++ue4\sync\engine\source\runtime\engine\private\ticktaskmanager.cpp:1474]
UE4Editor_Engine!UWorld::RunTickGroup() [d:\build\++ue4\sync\engine\source\runtime\engine\private\leveltick.cpp:783]
UE4Editor_Engine!UWorld::Tick() [d:\build\++ue4\sync\engine\source\runtime\engine\private\leveltick.cpp:1460]
UE4Editor_UnrealEd!UEditorEngine::Tick() [d:\build\++ue4\sync\engine\source\editor\unrealed\private\editorengine.cpp:1726]
UE4Editor_UnrealEd!UUnrealEdEngine::Tick() [d:\build\++ue4\sync\engine\source\editor\unrealed\private\unrealedengine.cpp:403]
UE4Editor!FEngineLoop::Tick() [d:\build\++ue4\sync\engine\source\runtime\launch\private\launchengineloop.cpp:3699]
UE4Editor!GuardedMain() [d:\build\++ue4\sync\engine\source\runtime\launch\private\launch.cpp:174]
UE4Editor!GuardedMainWrapper() [d:\build\++ue4\sync\engine\source\runtime\launch\private\windows\launchwindows.cpp:145]
UE4Editor!WinMain() [d:\build\++ue4\sync\engine\source\runtime\launch\private\windows\launchwindows.cpp:276]
UE4Editor!__scrt_common_main_seh() [f:\dd\vctools\crt\vcstartup\src\startup\exe_common.inl:283]
kernel32
ntdll`
```

Here's the error report, this does not happen in the version 4.20

**Comment by getnamo** [comment] 2019-03-14 21:40
May need blueprint graphs that trigger this or a minimal repro project

**Comment by Invius** [comment] 2019-03-15 10:15
First i'd like to thank you, i'm trying to make a integration of the google maps api, to show in a tutorial, to help people understand not just this pluggin which just for it would really helpful because there are no video tutorials for it, but to make a android gps integration for any project.

Here is a video showing the problems happening:
https://youtu.be/INxLcLQ2nng

Here are the two projects that you can see in the video that i am having problems with:
https://mega.nz/#!sFcF3SIb!FgJTGGswBdvRH1BpYwsezmS7XDJKGUsOlIhmpHPYhyI

**Comment by Invius** [comment] 2019-03-20 08:40
Is it possible to fix those problems?

**Comment by getnamo** [comment] 2019-03-27 21:16
Thanks for the detailed repro! Had a quick test and I unfortunately couldn't reproduce it on my end (scrolling doesn't do anything but it doesn't crash either). Atm I don't have more time to look into this and I'd recommend checking out the built-in engine widget instead https://docs.unrealengine.com/en-us/Engine/UMG/UserGuide/WidgetTypeReference/WebBrowser as it may provide what you need.

**Comment by Invius** [comment] 2019-03-28 08:24
> Thanks for the detailed repro! Had a quick test and I unfortunately couldn't reproduce it on my end (scrolling doesn't do anything but it doesn't crash either). Atm I don't have more time to look into this and I'd recommend checking out the built-in engine widget instead https://docs.unrealengine.com/en-us/Engine/UMG/UserGuide/WidgetTypeReference/WebBrowser as it may provide what you need.

With the browser on the engine you can not load local html files or even package with those. So that not a solution from what i need. But thanks anyway.

**Comment by getnamo** [comment] 2019-03-28 19:58
I remember scrolling working way back when I was using BLUI for a jam 

[Example gif of scrolling](https://i.imgur.com/oARViiA.gifv)

which used something like this for scrolling input 

![image](https://user-images.githubusercontent.com/542365/55188283-42ba7a80-5158-11e9-93c5-c03912f489ac.png)

and 

![image](https://user-images.githubusercontent.com/542365/55188466-b5c3f100-5158-11e9-8f02-54e9b1012a57.png)

for moving the cursor in the html widget. These look similar to what you're doing. I wonder if the BluEye object gets released from underneath you for some reason?

**Comment by o0pk2008** [comment] 2019-04-29 08:29
Mouse input does not work and POS is available

**Comment by getnamo** [comment] 2023-04-08 23:22
Closing due to age

**Closed by getnamo** 2023-04-08 23:22 UTC
Labels: bug, awaiting replicaiton
